#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-wagon-gitsite
Version  : 0.5
Release  : 1
URL      : https://github.com/stephenc/wagon-gitsite/archive/wagon-gitsite-0.5.tar.gz
Source0  : https://github.com/stephenc/wagon-gitsite/archive/wagon-gitsite-0.5.tar.gz
Source1  : https://repo1.maven.org/maven2/com/github/stephenc/wagon/wagon-gitsite/0.5/wagon-gitsite-0.5.jar
Source2  : https://repo1.maven.org/maven2/com/github/stephenc/wagon/wagon-gitsite/0.5/wagon-gitsite-0.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-wagon-gitsite-data = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
This is Kathryn Huxtable's gitsite wagon.
Code from Anthony Whitford <anthony@whitford.com> adds support for
multi-module projects.

%package data
Summary: data components for the mvn-wagon-gitsite package.
Group: Data

%description data
data components for the mvn-wagon-gitsite package.


%prep
%setup -q -n wagon-gitsite-wagon-gitsite-0.5

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/stephenc/wagon/wagon-gitsite/0.5
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/stephenc/wagon/wagon-gitsite/0.5/wagon-gitsite-0.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/stephenc/wagon/wagon-gitsite/0.5
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/stephenc/wagon/wagon-gitsite/0.5/wagon-gitsite-0.5.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/stephenc/wagon/wagon-gitsite/0.5/wagon-gitsite-0.5.jar
/usr/share/java/.m2/repository/com/github/stephenc/wagon/wagon-gitsite/0.5/wagon-gitsite-0.5.pom
